### ISSUE TITLE
Update Meeting Times

### ISSUE THREAD

**Issue by jrumacias** [HopliteSJSU/Club-Website#16]
Friday meetings still show as "TBD" and should be changed to "Fridays at 10:00 AM in MQH 226 (CSSL)."

CSSL is optional to add...up to you.

**Comment by philliprognerud** [comment]
Will deploy new changes tomorrow, along with backend changes completed by @NhatTrinh

**Comment by philliprognerud** [comment]
In order to make sure the text looks good on mobile screen's I have to shorten the lines to:

> Thursday 7:30PM @ MQH 234
> Friday 10:00AM @ MQH 226

**Comment by philliprognerud** [comment]
![image](https://user-images.githubusercontent.com/17166224/51805218-8dcf1480-221f-11e9-9fae-aea78ad267e5.png)

**Comment by philliprognerud** [comment]
#18
