### ISSUE TITLE
Muiltiple email signups in single session

### ISSUE THREAD

**Issue by jrumacias** [HopliteSJSU/Club-Website#17]
When tabling, we noticed that when someone enters their email on our site, it says "Success" and remains there. **Functionally, we are able to capture multiple emails in a single session**, but the response on the text bar _looks_ as though it is not ready to accept another email address.

**Comment by philliprognerud** [comment]
I see what you're saying. How do you want this implemented visually? Is it as simple as changing it to "Success! Please enter in another email" or do you want something more?

**Comment by jrumacias** [comment]
Maybe, have the success text display, then after a second or so, change back to the default text? this is cosmetic and not a big issue, so really whatever seems an intuitive fix to you.

**Comment by philliprognerud** [comment]
Makes sense, easy enough to fix. 

Do you also want the ability to submit multiple emails in on input bar? We have the backend functionality to do this already, but didn't seem like a practical use case for an average user.

**Comment by jrumacias** [comment]
single email response should be sufficient

**Comment by philliprognerud** [comment]
![input-bar](https://user-images.githubusercontent.com/17166224/51805615-97a74680-2224-11e9-9432-66c54e76b76e.gif)

Refer to #19
